EnglishGame/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hangman/',include("hangman.urls")),
]

hangman/urls.py
from django.urls import path
from . import views

app_name = "hangman"

urlpatterns = [
    path("", views.index, name="index"),  # Menu page
    # path("getCharacter/",views.getCharacter, name="getCharacter"),
]

hangman/models.py
from django.db import models

class wordBank(models.Model):
    word = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.word

hangman/views.py
# hangman/views.py
from django.shortcuts import render
from .models import wordBank

def index(request):
    word = None
    message = ''
    attemp = 3
    Guessed = ""
    if request.method == "POST":
        word = request.POST.get("word")
        guessCharacter = request.POST.get("guess").lower()
        Guessed = request.POST.get("Guessed")
        # print('ppppppppppp',Guessed)
        attemp = int(request.POST.get("attemp"))
        wordDisplay = request.POST.get("word-display")
        message = request.POST.get("message")

    
        if guessCharacter in Guessed:
            message = "you already guess this character"
        elif guessCharacter in word:
            Guessed += guessCharacter
            message = ''
        else:
            attemp -= 1
            Guessed += guessCharacter
            message = "Incorrect guess!"
        
        if attemp <= 0:
            message = f"Game Over! The word was: {word}"

        # print("QQQQQQQQQQQQQQQQQq",' '.join(list(Guessed)))
    if not word:
        word = getRandomWord()
    wordDisplay = processWordDisplay(word, Guessed)
    
    if wordDisplay.split(' ') == list(word):
        message = "Congratulations! You won!"
    return render(request,"hangman/game.html", {"word":word,
                                                "wordDisplay":wordDisplay,
                                                "Guessed": Guessed,
                                                "attemp": attemp,
                                                "message": message})


def getRandomWord(setWordForTest=None):
    if setWordForTest:
        word = wordBank.objects.filter(word=setWordForTest).first() 
    else:
        word = wordBank.objects.order_by("?").first() 

    return word.word

def processWordDisplay(word, guessedChar):
    if type(word) != str:
        print("word type is not string")
        raise TypeError("word type is not string")
    if type(guessedChar) != str:
        print("guessed character type is not string")
        raise TypeError("guessed character type is not string")
    temp = []
    word = word.lower()
    guessedChar  = guessedChar.lower()
    for char in word:
        if char in guessedChar:
            temp.append(char)
        else:
            temp.append("_")
    # print(">>>>>>",temp,word,guessedChar)
    return ' '.join(temp)

hangman/templates/hangman/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hangman</title>
    <script>
        console.log("{{Guessed}}")
    </script>
</head>
<body>
    <header>Welcome to Hangman</header>
    <!-- <p id = {{ word }}>{{ word }}</p> -->
    <form action="{% url 'hangman:index' %}" method="POST"> 
        {% csrf_token %}
        <input type="hidden" id="csrf_token" value="{{ csrf_token }}">
        <input type = "hidden" name = "word" id = "word" value="{{word}}">
        <input type = "hidden" name = "Guessed" value={{Guessed}}>
        <input type = "hidden" name = "attemp" id = "attemp" value="{{ attemp }}">
        <input type = "hidden" name = "message" value="{{ message }}">

        <p id = "word-display" value ={{wordDisplay}}>{{ wordDisplay }}</p>
        <input name="guess" id="guess-input" maxlength="1" required>
        <button type="submit" id ="submit-guess">Submit</button>
        <div>
            Guessed: <span id="guessed-letters">{{ Guessed|join:" " }}</span>
        </div>        
        <div type = "text" >
            attemp left : <span id = "attempts-left">{{ attemp }}</span>
        </div>
        <p id = "message">{{ message }}</p>
        
    </form>
</body>
</html>